jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8.5"
    steps:
    
        command: |
            sudo pip install pipenv
            pipenv install pillow
          - checkout
          - run: python3 app.py